/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

//Generated 26-feb-2013 16:30:23 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * AddressType generated by hbm2java
 */
@SuppressWarnings("serial")
@SequenceGenerator(name="addresstypes_id_seq", sequenceName="addresstypes_id_seq") 
@Entity
@Table(name = "addresstypes", schema = "public")
public class AddressType implements java.io.Serializable {

	private long id;
	private String type;
	private String subtype;
	
	public AddressType() {
	}

	public AddressType(long id, String type, String subtype) {
		this.id = id;
		this.type = type;
		this.subtype = subtype;
	}

	@Id
	@GeneratedValue(generator="addresstypes_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "subtype", nullable = false, length = 30)
	public String getSubtype() {
		return this.subtype;
	}

	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}
	
	/**
	 * Set the fields of this address type with the values from fields from other address type.
	 * @param otherAddressType Other address type
	 */
	@Transient
	public void setFromOtherAddressType(AddressType otherAddressType)
	{
		if (otherAddressType!=null)
		{
			setId(otherAddressType.getId());
			setType(otherAddressType.getType());
			setSubtype(otherAddressType.getSubtype());
		}
	}
	
	/**
	 * @return A copy of this address type.
	 */
	@Transient
	public AddressType getAddressTypeCopy()
	{
		return new AddressType(getId(),getType(),getSubtype());
	}
	
	@Override
	public boolean equals(Object obj)
	{
		return obj instanceof AddressType && getId()==((AddressType)obj).getId();
	}
}
