/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Answer generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@SequenceGenerator(name="answers_id_seq", sequenceName="answers_id_seq") 
@Table(name = "answers", schema = "public")
@Inheritance(strategy=InheritanceType.JOINED)
public class Answer implements java.io.Serializable {

	protected long id;
	protected Question question;
	protected Resource resource;
	protected String text;
	protected Boolean correct;
	protected Boolean fixed;
	protected int position;
	protected String name;
	protected int resourceWidth;
	protected int resourceHeight;

	public Answer() {
		this.correct = false;
		this.fixed = false;
		this.resource = null;
		this.resourceWidth = -1;
		this.resourceHeight = -1;
	}

	public Answer(long id) {
		this.id = id;
	}

	public Answer(long id, Question question, Resource resource, int resourceWidth, int resourceHeight, 
			String text, Boolean correct, Boolean fixed, int position, String name) {
		this.id = id;
		this.question = question;
		this.resource = resource;
		this.resourceWidth = resourceWidth;
		this.resourceHeight = resourceHeight;
		this.text = text;
		this.correct = correct;
		this.fixed = fixed;
		this.position = position;
		this.name = name;
	}

	@Id
	@GeneratedValue(generator="answers_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_question")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resource")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resources) {
		this.resource = resources;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "correct")
	public Boolean getCorrect() {
		return this.correct;
	}

	public void setCorrect(Boolean correct) {
		this.correct = correct;
	}

	@Column(name = "fixed")
	public Boolean getFixed() {
		return this.fixed;
	}

	public void setFixed(Boolean fixed) {
		this.fixed = fixed;
	}
	
	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "resource_width", nullable = false)
	public int getResourceWidth() {
		return this.resourceWidth;
	}

	public void setResourceWidth(int resourceWidth) {
		this.resourceWidth = resourceWidth;
	}

	@Column(name = "resource_height", nullable = false)
	public int getResourceHeight() {
		return this.resourceHeight;
	}

	public void setResourceHeight(int resourceHeight) {
		this.resourceHeight = resourceHeight;
	}
	
	/**
	 * Set the fields of this answer with the values from fields from other answer.
	 * @param otherAnswer Other answer
	 */
	@Transient
	public void setFromOtherAnswer(Answer otherAnswer)
	{
		if (otherAnswer!=null)
		{
			setId(otherAnswer.getId());
			setQuestion(otherAnswer.getQuestion());
			setResource(otherAnswer.getResource());
			setText(otherAnswer.getText());
			setCorrect(otherAnswer.getCorrect());
			setFixed(otherAnswer.getFixed());
			setPosition(otherAnswer.getPosition());
			setName(otherAnswer.getName());
			setResourceWidth(otherAnswer.getResourceWidth());
			setResourceHeight(otherAnswer.getResourceHeight());
		}
	}
	
	/**
	 * @return A copy of this answer.
	 */
	@Transient
	public Answer getAnswerCopy()
	{
		return new Answer(getId(),getQuestion(),getResource(),getResourceWidth(),getResourceHeight(),getText(),
			getCorrect(),getFixed(),getPosition(),getName());
	}
	
	/**
	 * @return OM answer component identifier
	 */
	@Transient
	public String getOmId()
	{
		StringBuffer omId=new StringBuffer("answer");
		omId.append(getPosition());
		return omId.toString();
	}
	
	@Override
	public boolean equals(Object obj)
	{
		boolean ok=false;
		if (obj instanceof Answer)
		{
			if (getId()==0L)
			{
				if (getQuestion()==null)
				{
					ok=((Answer)obj).getId()==0L && ((Answer)obj).getQuestion()==null && 
						getPosition()==((Answer)obj).getPosition();
				}
				else
				{
					ok=((Answer)obj).getId()==0L && getQuestion().equals(((Answer)obj).getQuestion()) && 
						getPosition()==((Answer)obj).getPosition();
				}
			}
			else
			{
				ok=getId()==((Answer)obj).getId();
			}
		}
		return ok;
	}
}
