/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

// Generated 16-mar-2012 12:07:33 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * FeedbackType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@SequenceGenerator(name="feedbacktypes_id_seq", sequenceName="feedbacktypes_id_seq") 
@Table(name = "feedbacktypes", schema = "public")
public class FeedbackType implements java.io.Serializable {

	private long id;
	private String type;
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

	public FeedbackType() {
	}

	public FeedbackType(long id, String type) {
		this.id = id;
		this.type = type;
	}

	public FeedbackType(long id, String type, Set<Feedback> feedbacks) {
		this.id = id;
		this.type = type;
		this.feedbacks = feedbacks;
	}

	@Id
	@GeneratedValue(generator="feedbacktypes_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedbackType")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

	/**
	 * Set the fields of this feedback type with the values from fields from other feedback type.
	 * @param otherFeedbackType Other feedback type
	 */
	@Transient
	public void setFromOtherFeedbackType(FeedbackType otherFeedbackType)
	{
		if (otherFeedbackType!=null)
		{
			setId(otherFeedbackType.getId());
			setType(otherFeedbackType.getType());
		}
	}
	
	@Override
	public boolean equals(Object obj)
	{
		return obj instanceof FeedbackType && getId()==((FeedbackType)obj).getId();
	}
}
