/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

//Generated 11-abr-2012 15:51:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
* NavLocation generated by hbm2java
*/
@SuppressWarnings("serial")
@Entity
@SequenceGenerator(name="navlocations_id_seq", sequenceName="navlocations_id_seq") 
@Table(name = "navlocations", schema = "public")
public class NavLocation implements java.io.Serializable {

	private long id;
	private String location;

	public NavLocation() {
	}

	public NavLocation(long id, String location) {
		this.id = id;
		this.location = location;
	}

	@Id
	@GeneratedValue(generator="navlocations_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "location", nullable = false, length = 30)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * Set the fields of this navigation location with the values from fields from other navigation location.
	 * @param otherNavLocation Other navigation location
	 */
	@Transient
	public void setFromOtherNavLocation(NavLocation otherNavLocation)
	{
		if (otherNavLocation!=null)
		{
			setId(otherNavLocation.getId());
			setLocation(otherNavLocation.getLocation());
		}
	}
	
	/**
	 * @return A copy of this navigation location.
	 */
	@Transient
	public NavLocation getNavLocationCopy()
	{
		return new NavLocation(getId(),getLocation());
	}
	
	@Override
	public boolean equals(Object obj)
	{
		return obj instanceof NavLocation && getId()==((NavLocation)obj).getId();
	}
}
