/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * QuestionsOmxml generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="questions_omxml",schema="public")
@PrimaryKeyJoinColumn(name="id_question")
public class OmXmlQuestion extends Question {
	
	private String xmlContent;
	
	public OmXmlQuestion()
	{
		super();
		this.xmlContent="";
		this.type="OM_XML";
	}

	public OmXmlQuestion(String xmlContent)
	{
		super();
		this.xmlContent=xmlContent;
	}
	
	@Column(name = "xml_content")
	public String getXmlContent() {
		return this.xmlContent;
	}

	public void setXmlContent(String xmlContent) {
		this.xmlContent = xmlContent;
	}
	
	@Override
	@Transient
	public void setFromOtherQuestion(Question otherQuestion)
	{
		super.setFromOtherQuestion(otherQuestion);
		if (otherQuestion instanceof OmXmlQuestion)
		{
			setXmlContent(((OmXmlQuestion)otherQuestion).getXmlContent());
		}
	}
}
