/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

//Generated 09-jul-2012 14:56:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PermissionType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@SequenceGenerator(name="permissiontypes_id_seq", sequenceName="permissiontypes_id_seq") 
@Table(name = "permissiontypes", schema = "public")
public class PermissionType implements java.io.Serializable {

	private long id;
	private String type;
	private Set<Permission> permissions = new HashSet<Permission>(0);

	public PermissionType() {
	}

	public PermissionType(long id, String type) {
		this.id = id;
		this.type = type;
	}

	@Id
	@GeneratedValue(generator="permissiontypes_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissionType")
	public Set<Permission> getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}

	/**
	 * Set the fields of this permission type with the values from fields from other permission type.
	 * @param otherPermissionType Other permission type
	 */
	@Transient
	public void setFromOtherPermissionType(PermissionType otherPermissionType)
	{
		if (otherPermissionType!=null)
		{
			setId(otherPermissionType.getId());
			setType(otherPermissionType.getType());
		}
	}
	
	@Override
	public boolean equals(Object obj)
	{
		return obj instanceof PermissionType && getId()==((PermissionType)obj).getId();
	}
}
