/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

// Generated 08-jul-2011 10:08:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.SequenceGenerator;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Transient;

/**
 * Categoria generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@SequenceGenerator(name="resources_id_seq", sequenceName="resources_id_seq") 
@Table(name = "resources", schema = "public")
public class Resource implements java.io.Serializable {

	private long id;
	private Category category;
	private String name;
	private String description;
	private String fileName;
	private String mimeType;
	private User user;
	private Copyright copyright;

	public Resource() {
		this(0L, null, null, null, null, null, null, null);
	}

	public Resource(long id, String name, String description, Category category, 
		User user, String fileName, String mimeType,Copyright copyright) {
		
		this.id = id;
		this.name = name;
		this.description = description;
		this.category = category;
		this.user = user;
		this.fileName = fileName;
		this.mimeType = mimeType;
		this.copyright = copyright;
	}

	@Id
	@GeneratedValue(generator="resources_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "file_name", nullable = true)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "mime_type", length = 30)
	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	@Column(name = "description", nullable = true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_category")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_copyright")
	public Copyright getCopyright() {
		return this.copyright;
	}

	public void setCopyright(Copyright copyright) {
		this.copyright = copyright;
	}

	/**
	 * Set the fields of this resource with the values from fields from other resource.
	 * @param otherResource Other resource
	 */
	@Transient
	public void setFromOtherResource(Resource otherResource)
	{
		if (otherResource!=null)
		{
			setId(otherResource.getId());
			setCategory(otherResource.getCategory());
			setName(otherResource.getName());
			setDescription(otherResource.getDescription());
			setFileName(otherResource.getFileName());
			setMimeType(otherResource.getMimeType());
			setUser(otherResource.getUser());
			setCopyright(otherResource.getCopyright());
		}
	}
	
	/**
	 * @return A copy of this resource.
	 */
	@Transient
	public Resource getResourceCopy()
	{
		return new Resource(
			getId(),getName(),getDescription(),getCategory(),getUser(),getFileName(),getMimeType(),getCopyright());
	}
	
	@Override
	public boolean equals(Object obj) {
		
		return obj instanceof Resource && getId()==((Resource)obj).getId();
	}
}
