/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

//Generated 11-abr-2012 15:51:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ScoreUnit generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@SequenceGenerator(name="scoreunits_id_seq", sequenceName="scoreunits_id_seq") 
@Table(name = "scoreunits", schema = "public")
public class ScoreUnit implements java.io.Serializable {

	private long id;
	private String unit;
	private Set<TestFeedback> testFeedbacks = new HashSet<TestFeedback>(0);

	public ScoreUnit() {
	}

	public ScoreUnit(long id) {
		this.id = id;
	}

	public ScoreUnit(long id, String unit, Set<TestFeedback> testFeedbacks) {
		this.id = id;
		this.unit = unit;
		this.testFeedbacks = testFeedbacks;
	}

	@Id
	@GeneratedValue(generator="scoreunits_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "unit", length = 30)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scoreUnit")
	public Set<TestFeedback> getTestFeedbacks() {
		return this.testFeedbacks;
	}

	public void setTestFeedbacks(Set<TestFeedback> testFeedbacks) {
		this.testFeedbacks = testFeedbacks;
	}

	/**
	 * Set the fields of this score unit with the values from fields from other score unit.
	 * @param otherScoreUnit Other score unit
	 */
	@Transient
	public void setFromOtherScoreUnit(ScoreUnit otherScoreUnit)
	{
		if (otherScoreUnit!=null)
		{
			setId(otherScoreUnit.getId());
			setUnit(otherScoreUnit.getUnit());
		}
	}
	
	@Override
	public boolean equals(Object obj)
	{
		return obj instanceof ScoreUnit && getId()==((ScoreUnit)obj).getId();
	}
}
