/* OpenMark Authoring Tool (GEPEQ)
 * Copyright (C) 2013 UNED
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package es.uned.lsi.gepec.model.entities;

//Generated 09-jul-2012 14:56:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * UserTypePermission generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@SequenceGenerator(name="usertypepermissions_id_seq", sequenceName="usertypepermissions_id_seq") 
@Table(name = "usertypepermissions", schema = "public")
public class UserTypePermission implements java.io.Serializable {

	private long id;
	private UserType userType;
	private Permission permission;
	private String value;

	public UserTypePermission() {
	}

	public UserTypePermission(long id, UserType userType,
			Permission permission, String value) {
		this.id = id;
		this.userType = userType;
		this.permission = permission;
		this.value = value;
	}

	@Id
	@GeneratedValue(generator="usertypepermissions_id_seq", strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usertype", nullable = false)
	public UserType getUserType() {
		return this.userType;
	}

	public void setUserType(UserType userType) {
		this.userType = userType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_permission", nullable = false)
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Set the fields of this permission of an user type with the values from fields from other permision 
	 * of an user type.
	 * @param otherUserTypePermission Other permission of an user type
	 */
	@Transient
	public void setFromOtherUserTypePermission(UserTypePermission otherUserTypePermission)
	{
		if (otherUserTypePermission!=null)
		{
			setId(otherUserTypePermission.getId());
			setUserType(otherUserTypePermission.getUserType());
			setPermission(otherUserTypePermission.getPermission());
			setValue(otherUserTypePermission.getValue());
		}
	}
	
	@Override
	public boolean equals(Object obj)
	{
		boolean ok=false;
		if (obj instanceof UserTypePermission)
		{
			if (getId()==0L)
			{
				ok=((UserTypePermission)obj).getId()==0L && 
					getUserType().equals(((UserTypePermission)obj).getUserType()) &&
					getPermission().equals(((UserTypePermission)obj).getPermission());
			}
			else
			{
				ok=getId()==((UserTypePermission)obj).getId();
			}
		}
		return ok;
	}
}
